font_family  Terminus (TTF)
bold_font    Terminus (TTF) Bold
font_size    13.5

window_padding_width 2

scrollback_lines 10000
# scrollback_pager lvim '+term' -
scrollback_pager less -R -
# scrollback_pager e -
adjust_line_height   -2
enable_audio_bell no
confirm_os_window_close 0
paste_actions quote-urls-at-prompt

open_url_with /home/evan/bin/copy

foreground #eeeeee
background #000000
# foreground #000000
# background #eeeeee


open_url_with firefox
mouse_click_url open_url

remember_window_size no
initial_window_width  800
initial_window_height 540

# --- Shortcuts ---
map ctrl+page_up scroll_page_up
map ctrl+page_down scroll_page_down

map ctrl+shift+minus change_font_size current -2
map ctrl+shift+equal change_font_size current +2
map ctrl+shift+0 change_font_size current 0

map ctrl+shift+y kitten hints --program "@" 
map shift+enter send_text all \e\r
