# Applies to ALL keyboards, including hotplugged USB/Bluetooth ones
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbModel" "pc105"
        Option "XkbOptions" "caps:super,compose:lwin,compose:ralt,keypad:pointerkeys"
EndSection
